language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.1
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.10
    - python: "3.3"
      env: DJANGO_VERSION=1.4.10
install:
  - pip install Django==$DJANGO_VERSION
  - pip install coveralls
script: coverage run tests.py
after_success:
    coveralls
